export {
  DOCUMENT_FONT_SIZE_PT as PDF_FONT_SIZE,
  DOCUMENT_LINE_HEIGHT as PDF_LINE_HEIGHT,
  DOCUMENT_PARAGRAPH_GAP_PT as PDF_PARAGRAPH_GAP,
  DOCUMENT_TASK_GAP_PT as PDF_TASK_GAP,
  DOCUMENT_SHEET_TITLE_SIZE_PT as PDF_SHEET_TITLE_SIZE,
  DOCUMENT_TASK_NUMBER_WIDTH_PT as PDF_TASK_NUMBER_WIDTH,
  DOCUMENT_PAGE_PADDING_V_PT as PDF_PAGE_PADDING_V,
  DOCUMENT_PAGE_PADDING_H_PT as PDF_PAGE_PADDING_H,
  DOCUMENT_TASK_INNER_GAP_PT as PDF_TASK_INNER_GAP,
  DOCUMENT_HEADER_BORDER_COLOR as PDF_HEADER_BORDER_COLOR,
  DOCUMENT_HEADER_MARGIN_BOTTOM_PT as PDF_HEADER_MARGIN_BOTTOM,
  DOCUMENT_HEADER_PADDING_BOTTOM_PT as PDF_HEADER_PADDING_BOTTOM,
} from "@/app/lib/documentTypography";
